[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "distributed-computation"
version = "0.1.0"
dependencies = [
    "dask[distributed]",
    "bokeh>=3.1.0"
]

[tool.setuptools.packages.find]
where = ["src"]
